### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by bpskishore** [confluentinc/common#174] opened 2018-12-02 03:14 UTC
[ERROR] Failed to execute goal on project common-metrics: Could not resolve dependencies for project io.confluent:common-metrics:jar:5.2.0-SNAPSHOT: The following artifacts could not be resolved: io.confluent:common-utils:jar:5.2.0-SNAPSHOT, io.confluent:assembly-plugin-boilerplate:zip:resources:5.2.0-SNAPSHOT: Failure to find io.confluent:common-utils:jar:5.2.0-SNAPSHOT in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by cricket007** [comment] 2019-01-04 22:19
Duplicates #170

**Comment by RoyalFeng** [comment] 2019-02-27 08:08
@cricket007  Do you solve this problem?

**Comment by ouertani** [comment] 2019-03-10 12:31
> @cricket007 Do you solve this problem?

yes

**Comment by ewencp** [comment] 2019-03-12 20:03
Agreed this is a dupe of #170. See that issue for explanation of how to build, including dependencies.

**Closed by ewencp** 2019-03-12 20:03 UTC
